name: deploy to heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: "d5507648-36be-473f-b709-f808fc8027b4"
          heroku_app_name: "auto-tindr-frontend"
          heroku_email: "kamalovaalbina1410@gmail.com"
